### ISSUE TITLE
presumably erroneous character in ot:originalLabel

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/phylografter#100]
For study 230, otu with id=otu61228 has ot:originalLabel="Petiveria \u001b"
where the funky unicode is the ESC character. 

My roundtrip code (which uses python's xml.dom.minidom to write XML) writes it to XML without complaining, but then can't read the resulting XML. I'm not sure if this is a bug in minidom or some forbidden character that is not supposed to be allowed in an XML element's text content. So I'm hesitant to submit it as a minidom bug.

In general, I don't really like editing the field for ot:originalLabel in the db, but:
1. that seems like the easiest fix, and
2. it seems unlikely that character was in the original file.

So maybe editing the phylografter db is the appropriate fix?

**Comment by rhr** [comment]
Label changed to Petiveria in phylografter db.
