### ISSUE TITLE
node with otu ids that are not valid

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/phylografter#102]
There are several cases, summarized at http://phylo.bio.ku.edu/tmp/nodes_with_invalid_otu_ids.txt

**Comment by zbolander** [comment]
I'll re-upload re-map the studies and see if that helps. A lot of the
earlier phylografter uploads had problems of various sorts.

Bryan

**Comment by mtholder** [comment]
Hi Bryan, if the remapping is time-consuming and these studies are not needed, we could just delete them. i don't know how important those studies are. the list came from a script run over every study in the entire corpus.

**Comment by jar398** [comment]
Along these lines, although I think not the same problem:

When the taxonomy gets updated some of the OTT ids become deprecated, for a
variety of reasons that I won't go into here. In some but not all cases a
replacement id is stored in a column of the file deprecated.tsv in the
taxonomy dump. I had anticipated that most problems would be fixed through
some automatic process such as use of the deprecated.tsv files and
application of the TNRS. These fixes would be applied in the curation
interface, in treemachine, or in both. Treemachine applies the TNRS I
believe in this situation. Re-entering the study is probably the wrong
approach in general as the issue applies to all studies and doing manual
remapping does not scale.

**Comment by rhr** [comment]
Let's hold off deleting stuff until I have a chance to look at those
studies in particular and do some database curation.

**Comment by rhr** [comment]
I think the update to ott 2.4 will fix this.
