### ISSUE TITLE
reference to non existent otu

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/phylografter#105]
In study 156, the NexSON emitted has a node (id=node169654) that refers to otu66806 
but no otu with that ID is in the otus.

**Comment by mtholder** [comment]
also otu66806 in study 160 for node node170768

**Comment by mtholder** [comment]
and:
  otu66779 in study 155 for node169606
  otu69164 in study 191 for node176168
  otu66894 in study 157 for node169803
  otu68239 in study 178 for node173114
  otu65909 in study 143 for node167772

**Comment by rhr** [comment]
These were database corruptions from a past bug, now fixed. Please test.

**Comment by mtholder** [comment]
Yup. That fixed it. thanks.
