### ISSUE TITLE
Phylografter not recognizing update to study

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/phylografter#112]
When adding the ingroup to a tree, while remaining in phylografter (fixed since #108 ), it nevertheless is not tagged as 'updated' by the nexson export machinery. Adding tags is similar: the study is not pulled as 'updated'. Have got it to work by adding dummy comments into the "Edit Record".

**Comment by rhr** [comment]
I think this is fixed - @josephwb please test, and close if so. Thanks!

**Comment by josephwb** [comment]
Looks good. Thanks!
