### ISSUE TITLE
provide a way to delete studies/trees

### ISSUE THREAD

**Issue by rhr** [OpenTreeOfLife/phylografter#12]
This raises questions about who should be able to delete -- the submitter only? A group?

As a first pass I'll make it so that studies/trees can be deleted only by the submitter.

**Comment by kcranston** [comment]
I think that is a reasonable decision for a first implementation.

On Sat, Dec 8, 2012 at 9:56 AM, Rick Ree notifications@github.com wrote:

> This raises questions about who should be able to delete -- the submitter
> only? A group?
> 
> As a first pass I'll make it so that studies/trees can be deleted only by
> the submitter.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/OpenTreeOfLife/phylografter/issues/12.

## 

```
karen.cranston@gmail.com
@kcranstn
```

**Comment by pmidford** [comment]
The modified_list service will need a way to indicate that the modification of the tree/study was that it was deleted.

**Comment by lcoghill** [comment]
Done. See #91.
