### ISSUE TITLE
Focal clade listed as optional, but seems to be required

### ISSUE THREAD

**Issue by lcoghill** [OpenTreeOfLife/phylografter#123]
When attempting to submit a study without a Focal clade, or a Focal clade not in the database the error "Value not in database" is issued.

**Comment by lcoghill** [comment]
Seems to be a glitch with the auto-complete widget when suggesting names.

**Comment by jimallman** [comment]
Basic autocomplete and choosing works for me ![as seen here](https://cloud.githubusercontent.com/assets/446375/3153043/070cde02-ea96-11e3-9ed7-38ddea7b6221.png). But then all values seem to fail validation ("Value not in database"). Apparently the RETURN key is submitting the form prematurely, so this may be a false alarm.

**Comment by lcoghill** [comment]
Poor wording on my part. The issue is about the fact that the focal clade is listed as optional, and it seems it has to be one of the clades from autocomplete in order to submit a new study. I think this was also the issue when trying to delete a study (see issue #120) with a empty focal clade. The focal clade in the form was empty, not one from autocomplete so it would give the same error. 
![phylografter-error](https://cloud.githubusercontent.com/assets/5216482/3162316/18a79258-eb34-11e3-96e2-94204c134d31.png)

**Comment by lcoghill** [comment]
Fixed. 6a1b63e18b
