### ISSUE TITLE
2 OTUs not mapping with GB#s. Study 2927

### ISSUE THREAD

**Issue by hdliv** [OpenTreeOfLife/phylografter#124]
An undergrad working with us this summer passed me this information.

These are not mapping with GB#s
JQ955541 (Apoholosticha sinica) & KF730314 Tetrakeronopsis silvanetoi

**Comment by jar398** [comment]
These aren't in the taxonomy. This should be reported as a taxonomy issue.

A source taxonomy would need to be found that contains these names, and
imported. Alternatively the patch system could be used to add them.
https://github.com/OpenTreeOfLife/reference-taxonomy/wiki/Interim-taxonomy-patch-feature

Jonathan

On Mon, Jun 2, 2014 at 2:01 PM, Dail Laughinghouse <notifications@github.com

**Comment by hdliv** [comment]
@jar398 Thank you.  I added a patch.
