### ISSUE TITLE
service to list studies added/changed since a given time

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/phylografter#26]
In order to synchronize treemachine with phylografter's tree corpus, there needs to be a service that lists all studies that have been added or changed since a given time. This will allow treemachine to poll periodically for new stuff. Given the list, it can then iterate to fetch each new study (#25). @pmidford

**Comment by jar398** [comment]
In addition to the study identifier list, the API should return the date/time, according to phylografter's local clock, at which the list is current.  This value can then be remembered by the client and used on the _next_ call to the API. (Clock skew defense)

**Comment by pmidford** [comment]
This appears to be working in 'production.'
