### ISSUE TITLE
look up bibliographic citation from DOI

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/phylografter#3]
Since the reference details can be obtained from the DOI (via HTTP GET from dx.doi.org with appropriate conneg), there is no need to enter a bibliographic reference, as long as the DOI is given. Allow people to enter DOI only. See http://crosscite.org/cn/

DOIs should be normalized to http://dx.doi.org/10.... per Crossref's instructions. See http://www.crossref.org/02publishers/doi_display_guidelines.html

**Comment by mtholder** [comment]
I'll take a stab at working on this...

**Comment by mtholder** [comment]
Need to allow doi: in doi's entered and allow DOI's with more than 1 / (e.g. 10.1093/sysbio/sys026 ). I can fix these issues

**Comment by mtholder** [comment]
Should be fixed now (with commit 474f9d775294dcebd05909e713e640c6b58a1b14 ). I'll leave this issue open for a bit, just in case more issues crop up.

**Comment by mtholder** [comment]
Jonathan emailed me about getting the python controller to strip off http://dx.dio.org/
That is now done, and the code should now deal with unicode returned by the  http://dx.doi.org/ web service.

**Comment by rhr** [comment]
Ok, I will close this then. Thanks!
