### ISSUE TITLE
ottolid value of null in nexson export

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/phylografter#37]
Example [here](http://www.reelab.net/phylografter/study/export_NexSON.json/14). See entry:

{"@label": "Parmentiera cerifera", "meta": {"@property": "ot:ottolid", "@xsi:type": "nex:LiteralMeta", "$": null}

Perhaps this is just an older example, and will go away with updating? 

Otherwise, if no ottolid exists, the meta property should probably also not exist. Or NexsonReader can be made to handle null. What is the plan here?

**Comment by pmidford** [comment]
Agree, the exporter shouldn't be generating this - there shouldn't be a null value to begin with, but that's a different issue from the exporter displaying it.

-Peter

**Comment by josephwb** [comment]
Seems fixed. Closing.
