### ISSUE TITLE
ingroups annotation should be included in exported nexons

### ISSUE THREAD

**Issue by blackrim** [OpenTreeOfLife/phylografter#59]
The clade that is labeled as ingroup should be annotated as such in the exported nexson.

**Comment by blackrim** [comment]
A couple of examples include study 266 and 61

**Comment by josephwb** [comment]
There may have been confusion over what was desired. We would like (for those studies with the property) to have the ingroup annotation exported, not the focal clade property.

**Comment by pmidford** [comment]
Thanks, I'll take a look for these.

-Peter

**Comment by pmidford** [comment]
Ok, I have a list of trees with multiple nodes tagged as ingroups.  There is only one tree (study 762, Tree 1418 - 'parsimony') that appears to have incompatible ingroup tags (sister leaf nodes both labelled Forsterella nowickii). This needs attention.  There are another 17 trees with 2 ingroup nodes, but one is a descendent of the other in this case, so I just choose the one closer to root.

**Comment by josephwb** [comment]
Do we know who uploaded these? They should be informed that this is not
correct.

Joseph.

**Comment by pmidford** [comment]
We have contributor names - I'm putting together a list now.  We should probably get the visual indication of ingroup nodes working before contacting anyone - a lot of these nodes don't have labels and I don't think the phylografter node ids will be useful to anyone other than Rick.

**Comment by josephwb** [comment]
This is working on both ends.
