### ISSUE TITLE
Make unmatched OTU's more obvious

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/phylografter#7]
Blank or Red-text  Taxon fields in DOMAIN/phylografter/otu/study/#### would help.

Workaround: clicking taxon header to sort by that column, puts unmatched up top, which is quite helpful

Defaulting to sorting by the taxon header might be best for studies in which not all OTU's are matched

**Comment by cbaron** [comment]
Because I found it incredibly difficult to get the table to sort by taxon by default, I got rid of the data table plugin for this page and wrote my own.  It now sorts with unmatched OTU's on top..  Let me know if there's anything else wanted.
