### ISSUE TITLE
Make sure that all OTT synonyms are in ottol_name table

### ISSUE THREAD

**Issue by rhr** [OpenTreeOfLife/phylografter#71]
From Jonathan:

The OTU matching completion box offers Cochliobolus heterostrophus C4, but not Cochliobolus heterostrophus. Both are in the synonyms list.

I think Botrytis globosa is similar.

These are from studies 1164 and 1045.

**Comment by jar398** [comment]
Here are some other names that are in the OTT 2.0 synonyms list but missing from the Phylografter OTU completion tool:

Agaricus agrinferus
Camarops rogersii
Cladosporium allicinum
Diaporthe gulyae
Gnomoniopsis paraclavulata
Herpotrichia nigra
Hyphoderma macaronesicum
Colletotrichum cordylinicola

(Via Romina)
