### ISSUE TITLE
Does adding an ingroup annotation make a study show up in the modified_list web service?

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/phylografter#75]
The study/status app is using the PHYLOGRAFTER/study/modified_list.json/url web service to detect if it needs to update a tree.
Looking at the code for phylografter (specifically update_snode in snode.py and modified_list in study.py), it appears that adding an ingroup annotation to a tree will not update the tree or the study's modification time. Thus these changes won't be pulled down by the status app.

Can someone a bit more familiar with phylografter confirm that? If that is correct, I think that we need to change the behavior so that we can tell that the study has changed.

**Comment by pmidford** [comment]
Mark,
        I can confirm that. I'll take care of it.
-Peter

**Comment by pmidford** [comment]
This should now be fixed.
