### ISSUE TITLE
treebase import tree labels

### ISSUE THREAD

**Issue by blackrim** [OpenTreeOfLife/phylografter#85]
Treebase import seems to be randomizing the names of the trees on import. For example http://www.reelab.net/phylografter/study/view/2044 has the wrong tree labels for the newick trees.

**Comment by rhr** [comment]
What do you mean by wrong, and how can you tell? It would help if you could
point to a specific tree and tip, thanks.

It does seem to the case that the trees in the NexML document do not match
exactly the trees shown in the figures, but that's not a phylografter issue.

**Comment by blackrim** [comment]
Yeah, it isn't that the species labels are wrong (maybe they are but that
isn't the issue). If you look at the "all genes" tree from phylografter and
compare it to the all genes from treebase (Tr61313) you will see that
Triphysaria pusilla is sister to some Castilleja (this is phylografter). In
the Tr61313 (all genes from treebase) it goes
like (Triphysaria_floribunda,Triphysaria_pusilla). So something is
different here. It appears that the tree that is "all genes" in
phylografter is actually the phyA 112 tree from Treebase based on sharing
this relationship
(Triphysaria_pusilla:0.020768107312199288,(Castilleja_rubicundula:0.021928846684613472,Castilleja_tenuis:0.019600581062418986):0.0022622862476955143).

**Comment by rhr** [comment]
This is a user error. The tree labeled 'all genes' is actually treebase
tree Tr61315 (PhyA 112).

**Comment by rhr** [comment]
I fixed the tree labels for study 2044.
