### ISSUE TITLE
invalid export of nexson: tree's edge referring to a non-existent node ID

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/phylografter#97]
Getting the NeXSON for study using the study/export_gzipNexSON.json web service call results in:
###### 

[snip]
"@id": "tree274", 
"edge": [
{
"@id": "edge190736", 
"@source": "node3", 
"@target": "node190736"
}, 
[snip]
###### 

but the source node for this edge (node3) is not an ID that I can find in the file.

**Comment by pmidford** [comment]
I'll have a look at this.
-Peter

**Comment by pmidford** [comment]
There seems to be something broken in the database:

mysql> select parent from snode where id = 190736;
+--------+
| parent |
+--------+
|      3 |
+--------+
1 row in set (0.00 sec)

but
mysql> select tree from snode where id = 3;
+------+
| tree |
+------+
|    1 |
+------+
1 row in set (0.00 sec)

Rick - what's the best way to proceed here?

-Peter

**Comment by rhr** [comment]
Strange - snode 190736 is the root node of stree 274 and its parent should
be NULL. There seems to be 11 cases like this. I'll fix them manually in
the db and hope that it doesn't happen again...

**Comment by rhr** [comment]
Database is updated now and new sql dump being generated. To update a local mysql instance, do

update snode set parent = NULL where next = 1 and parent IS NOT NULL;
